In [19]:
import pandas as pd

train_df = pd.read_csv("/content/drive/MyDrive/financial_transactions_train.csv")


print('train data')
print(train_df.head())
print(train_df.shape)

train data
                              Transaction_Text       Label
0  Education loan EMI - INR 48395 - Ref 776405         EMI
1    NPS contribution - INR 24678 - Ref 554441  Investment
2   eBay online order - INR 21649 - Ref 863410    Shopping
3     Credit card EMI - INR 11866 - Ref 611973         EMI
4        Car loan EMI - INR 20537 - Ref 317418         EMI
(5000, 2)

In [20]:
test_df = pd.read_csv("/content/drive/MyDrive/financial_transactions_test.csv")

print(test_df.head())
print(test_df.shape)
print(test_df.columns)

                              Transaction_Text       Label
0  Mobile EMI payment - INR 45866 - Ref 955127         EMI
1  Education loan EMI - INR 32772 - Ref 858630         EMI
2       Bike loan EMI - INR 12852 - Ref 259771         EMI
3    PPF contribution - INR 10392 - Ref 505075  Investment
4     NPS contribution - INR 3583 - Ref 580994  Investment
(1000, 2)
Index(['Transaction_Text', 'Label'], dtype='object')

In [21]:
print("\nMissing values:")
print(train_df.isnull().sum())

Missing values:
Transaction_Text    0
Label               0
dtype: int64

In [22]:
print("\nDuplicate rows:")
print(train_df.duplicated().sum())

Duplicate rows:
0

In [23]:
print("\nClass distribution:")
print(train_df["Label"].value_counts())

Class distribution:
Label
Investment    1058
EMI            999
Shopping       997
Travel         975
Food           971
Name: count, dtype: int64

In [24]:
import re

def clean_text(text):
    text = text.lower()

    # Remove INR amount
    text = re.sub(r'\binr\s*\d+(?:\.\d+)?\b', '', text)

    # Remove reference number
    text = re.sub(r'\bref\s*\d+\b', '', text)

    # Remove hyphens
    text = re.sub(r'-+', ' ', text)

    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text

train_df["Clean_Text"] = train_df["Transaction_Text"].apply(clean_text)

print(train_df[["Transaction_Text", "Clean_Text", "Label"]].head(20))

                                     Transaction_Text  \
0         Education loan EMI - INR 48395 - Ref 776405
1           NPS contribution - INR 24678 - Ref 554441
2          eBay online order - INR 21649 - Ref 863410
3            Credit card EMI - INR 11866 - Ref 611973
4               Car loan EMI - INR 20537 - Ref 317418
5            Credit card EMI - INR 17358 - Ref 776864
6     Stock market investment - INR 3515 - Ref 966760
7        Metro card recharge - INR 31664 - Ref 344965
8       Electronics purchase - INR 20742 - Ref 689191
9        Bus ticket purchase - INR 46011 - Ref 472828
10        Grocery food items - INR 24352 - Ref 450218
11             Bike loan EMI - INR 43378 - Ref 474875
12        Grocery food items - INR 15852 - Ref 169806
13  Fixed deposit investment - INR 15964 - Ref 968375
14          PPF contribution - INR 25330 - Ref 784494
15       Cafe coffee purchase - INR 3139 - Ref 599962
16            PPF contribution - INR 875 - Ref 642625
17   Restaurant dine-in bill - INR 19055 - Ref 558430
18   Stock market investment - INR 37521 - Ref 810126
19          Uber ride payment - INR 8021 - Ref 122858

                  Clean_Text       Label
0         education loan emi         EMI
1           nps contribution  Investment
2          ebay online order    Shopping
3            credit card emi         EMI
4               car loan emi         EMI
5            credit card emi         EMI
6    stock market investment  Investment
7        metro card recharge      Travel
8       electronics purchase    Shopping
9        bus ticket purchase      Travel
10        grocery food items        Food
11             bike loan emi         EMI
12        grocery food items        Food
13  fixed deposit investment  Investment
14          ppf contribution  Investment
15      cafe coffee purchase        Food
16          ppf contribution  Investment
17   restaurant dine in bill        Food
18   stock market investment  Investment
19         uber ride payment      Travel

In [25]:
train_df["Clean_Text"] = train_df["Transaction_Text"].apply(clean_text)

In [26]:
train_df.head()

                              Transaction_Text       Label          Clean_Text
0  Education loan EMI - INR 48395 - Ref 776405         EMI  education loan emi
1    NPS contribution - INR 24678 - Ref 554441  Investment    nps contribution
2   eBay online order - INR 21649 - Ref 863410    Shopping   ebay online order
3     Credit card EMI - INR 11866 - Ref 611973         EMI     credit card emi
4        Car loan EMI - INR 20537 - Ref 317418         EMI        car loan emi

In [27]:
import re

def clean_text(text):
    text = text.lower()

    # Remove INR amount
    text = re.sub(r'\binr\s*\d+(?:\.\d+)?\b', '', text)

    # Remove reference number
    text = re.sub(r'\bref\s*\d+\b', '', text)

    # Remove hyphens
    text = re.sub(r'-+', ' ', text)

    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text

test_df["Clean_Text"] = test_df["Transaction_Text"].apply(clean_text)

print(test_df[["Transaction_Text", "Clean_Text", "Label"]].head(20))

                                  Transaction_Text             Clean_Text  \
0      Mobile EMI payment - INR 45866 - Ref 955127     mobile emi payment
1      Education loan EMI - INR 32772 - Ref 858630     education loan emi
2           Bike loan EMI - INR 12852 - Ref 259771          bike loan emi
3        PPF contribution - INR 10392 - Ref 505075       ppf contribution
4         NPS contribution - INR 3583 - Ref 580994       nps contribution
5    Electronics purchase - INR 25775 - Ref 761604   electronics purchase
6       Hotel dinner bill - INR 16135 - Ref 592344      hotel dinner bill
7      IRCTC train ticket - INR 33490 - Ref 509896     irctc train ticket
8    Zomato food delivery - INR 37155 - Ref 672579   zomato food delivery
9    Myntra fashion order - INR 11689 - Ref 528365   myntra fashion order
10    Metro card recharge - INR 21609 - Ref 859684    metro card recharge
11          Appliance EMI - INR 24071 - Ref 609771          appliance emi
12        Credit card EMI - INR 41177 - Ref 373207        credit card emi
13   Zomato food delivery - INR 15260 - Ref 991890   zomato food delivery
14         Mutual fund SIP - INR 8157 - Ref 826477        mutual fund sip
15     Hotel stay booking - INR 22916 - Ref 424748     hotel stay booking
16           ETF purchase - INR 17463 - Ref 528534           etf purchase
17   Cafe coffee purchase - INR 35889 - Ref 672180   cafe coffee purchase
18   Gold bond investment - INR 25833 - Ref 671990   gold bond investment
19  Retail store shopping - INR 49136 - Ref 630407  retail store shopping

         Label
0          EMI
1          EMI
2          EMI
3   Investment
4   Investment
5     Shopping
6         Food
7       Travel
8         Food
9     Shopping
10      Travel
11         EMI
12         EMI
13        Food
14  Investment
15      Travel
16  Investment
17        Food
18  Investment
19    Shopping

In [28]:
test_df["Clean_Text"] = test_df["Transaction_Text"].apply(clean_text)

In [29]:
test_df.head()

                              Transaction_Text       Label          Clean_Text
0  Mobile EMI payment - INR 45866 - Ref 955127         EMI  mobile emi payment
1  Education loan EMI - INR 32772 - Ref 858630         EMI  education loan emi
2       Bike loan EMI - INR 12852 - Ref 259771         EMI       bike loan emi
3    PPF contribution - INR 10392 - Ref 505075  Investment    ppf contribution
4     NPS contribution - INR 3583 - Ref 580994  Investment    nps contribution

In [30]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    ngram_range=(1, 2)
)

X_train = vectorizer.fit_transform(train_df["Clean_Text"])
y_train = train_df["Label"]

In [31]:
X_test = vectorizer.transform(test_df["Clean_Text"])
y_test = test_df["Label"]

In [32]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42)

In [33]:
y_pred = model.predict(X_test)

In [34]:
comparison = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": y_pred
})

print(comparison.head(20))

        Actual   Predicted
0          EMI         EMI
1          EMI         EMI
2          EMI         EMI
3   Investment  Investment
4   Investment  Investment
5     Shopping    Shopping
6         Food        Food
7       Travel      Travel
8         Food        Food
9     Shopping    Shopping
10      Travel      Travel
11         EMI         EMI
12         EMI         EMI
13        Food        Food
14  Investment  Investment
15      Travel      Travel
16  Investment  Investment
17        Food        Food
18  Investment  Investment
19    Shopping    Shopping

In [35]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Test Accuracy:", accuracy)

Test Accuracy: 1.0

In [48]:
new_transactions = [
     "Paid monthly installment for my smartphone",
    "Swiggy order for dinner tonight",
    "Bought new clothes from an online store",
    "Booked a cab to the railway station",
    "Started a monthly mutual fund SIP",
    "Laptop monthly installment payment",
    "Ordered pizza for lunch",
    "Purchased shoes from an online shopping website",
    "Uber ride payment",
    "Invested money in a gold bond",
    "Paid my bike loan installment",
    "Coffee and breakfast at a cafe",
    "Bought groceries from supermarket",
    "Flight ticket booking payment",
    "Credit card installment payment",
    "Purchased an ETF",
    "Dinner at a restaurant",
    "Metro travel card recharge",
    "Bought a new shirt online",
    "Added money to my NPS account"

]

new_clean = [clean_text(x) for x in new_transactions]

new_tfidf = vectorizer.transform(new_clean)

predictions = model.predict(new_tfidf)

for text, prediction in zip(new_transactions, predictions):
    print(text, "→", prediction)

Paid monthly installment for my smartphone → Investment
Swiggy order for dinner tonight → Food
Bought new clothes from an online store → Shopping
Booked a cab to the railway station → Travel
Started a monthly mutual fund SIP → Investment
Laptop monthly installment payment → EMI
Ordered pizza for lunch → Food
Purchased shoes from an online shopping website → Shopping
Uber ride payment → Travel
Invested money in a gold bond → Investment
Paid my bike loan installment → EMI
Coffee and breakfast at a cafe → Food
Bought groceries from supermarket → Shopping
Flight ticket booking payment → Travel
Credit card installment payment → EMI
Purchased an ETF → Investment
Dinner at a restaurant → Food
Metro travel card recharge → Travel
Bought a new shirt online → Shopping
Added money to my NPS account → Investment

In [37]:
# from sklearn.model_selection import train_test_split

# X = train_df["Clean_Text"]
# y = test_df["Label"]

# X_train, X_test, y_train, y_test = train_test_split(
#     X,
#     y,
#     test_size=0.20,
#     random_state=42,
#     stratify=y
# )

# print("Training samples:", len(X_train))
# print("Testing samples:", len(X_test))

**TF-IDF (Term Frequency-Inverse Document Frequency)** is a statistical score that evaluates how important a word is to a document in a collection (corpus) of documents.

In [38]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [39]:
# vectorizer = TfidfVectorizer(
#     ngram_range=(1, 2)
# )

In [40]:
# X_train_tfidf = vectorizer.fit_transform(X_train)
# X_test_tfidf = vectorizer.transform(X_test)

In [41]:
# print("Training shape:", X_train_tfidf.shape)
# print("Testing shape:", X_test_tfidf.shape)

In [42]:
# print("\nVocabulary:")
# print(vectorizer.get_feature_names_out())

In [43]:
# from sklearn.linear_model import LogisticRegression

# lr_model = LogisticRegression(
#     max_iter=1000,
#     random_state=42
# )

# lr_model.fit(X_train_tfidf, y_train)

In [44]:
# y_pred = lr_model.predict(X_test_tfidf)
# print(y_pred[:20])

In [45]:
# from sklearn.metrics import accuracy_score

# accuracy = accuracy_score(y_test, y_pred)

# print("Accuracy:", accuracy)

In [46]:
# from sklearn.metrics import classification_report, confusion_matrix

# print("Classification Report:")
# print(classification_report(y_test, y_pred))

# print("\nConfusion Matrix:")
# print(confusion_matrix(y_test, y_pred))

In [49]:
print("Duplicate rows:", train_df.duplicated().sum())

print("Duplicate Transaction_Text:",
      train_df["Transaction_Text"].duplicated().sum())

print("Duplicate Clean_Text:",
      train_df["Clean_Text"].duplicated().sum())

Duplicate rows: 0
Duplicate Transaction_Text: 0
Duplicate Clean_Text: 4950